Added publishEndpoint method in Consensus contract; Added EventDecode…
OpenST/compute pull request #106
Opened 2019-12-10 09:00 UTC by gulshanvasnani

PR contains changes to add:
1. **publishEndpoint** method.
2. Event decoder.
3. Unit test cases

fixes #85

2019-12-11 10:46 UTC, sarvesh-ost commented on contracts/consensus/Consensus.sol
> +            "Invalid metachain id"
```suggestion
            "No core exists for the metachain id."
```

2019-12-11 12:52 UTC, gulshanvasnani commented on contracts/consensus/Consensus.sol
> +            "Invalid metachain id"
Done

2019-12-12 07:55 UTC, deepesh-kn requested changes
👍 
few small changes.

2019-12-12 07:55 UTC, deepesh-kn commented on contracts/consensus/Consensus.sol
> +    /* Events */
As per the guidelines, add a new line before events.

2019-12-12 07:55 UTC, deepesh-kn commented on contracts/consensus/Consensus.sol
> +        string _endpoint
Remove the `_`'s

2019-12-12 07:55 UTC, deepesh-kn commented on contracts/test/core/SpyCore.sol
> +
As its not used in tests, please add an assert to break if its called.
```
// This is not used in test so break
        require(false, "This should not be called for unit tests.");
```

2019-12-12 07:55 UTC, deepesh-kn commented on contracts/test/core/MockCore.sol
> +    function activateValidator(
```suggestion
    function addValidator(
```

2019-12-12 09:08 UTC, gulshanvasnani commented on contracts/consensus/Consensus.sol
> +    /* Events */
Done.

2019-12-12 09:29 UTC, gulshanvasnani commented on contracts/consensus/Consensus.sol
> +        string _endpoint
Done.

2019-12-12 09:29 UTC, gulshanvasnani commented on contracts/test/core/SpyCore.sol
> +
Done

2019-12-12 09:29 UTC, gulshanvasnani commented on contracts/test/core/MockCore.sol
> +    function activateValidator(
Done

2019-12-12 09:31 UTC, gulshanvasnani commented on contracts/test/core/SpyCore.sol
> +
Done

2019-12-12 11:44 UTC, deepesh-kn approved these changes
LGTM 👍

2019-12-12 11:45 UTC, merged