Core unit tests
OpenST/compute pull request #15
Opened 2019-11-01 10:55 UTC by pgev

2019-11-18 14:55 UTC, deepesh-kn requested changes
Looks good to me. 👍 
Maybe we can add some more tests.
1. Unit tests to assert constants.
2. Unit tests for the variables/properties.

There are a few inline comments.

2019-11-18 14:55 UTC, deepesh-kn commented on test/core/join.js
> +        'The core must be running..',
```suggestion
        'The core must be running.',
```

2019-11-18 14:55 UTC, deepesh-kn commented on test/core/join.js
> +
Unit tests for the following conditions are missing:
1. Begin height cannot be less than kernel height.
2. Validator must not have a non-zero begin height
3. Maximum number of validators that can join in one metablock is reached.

Maybe some of these conditions cannot occur. In that case should we remove this from the code?

2019-11-18 14:55 UTC, deepesh-kn commented on test/core/join_during_creation.js
> +
Missing test cases: 
1. Proposal set has already been initialised at this height.
2. Begin height cannot be less than kernel height.
3. Validator must not have a non-zero begin height

Maybe some of these conditions cannot occur. In that case should we remove this from the code?

2019-11-18 14:55 UTC, deepesh-kn commented on test/core/join_during_creation.js
> +      assertConfigInCreation(config.mockCore);
Why is `assertConfigInCreation` needed here.

2019-11-18 14:55 UTC, deepesh-kn commented on test/core/join_during_creation.js
> +});
The value of the proposal should be asserted.
`proposals[openKernelHeight][SENTINEL_PROPOSALS] = SENTINEL_PROPOSALS;`

2019-11-18 14:55 UTC, deepesh-kn commented on test/core/open_metablock.js
> +    });
Assert value of `quorum`

2019-11-18 14:55 UTC, deepesh-kn commented on test/core/open_metablock.js
> +    });
One more test can be added when `proposal set has already been initialized at this height`

2019-11-18 14:55 UTC, deepesh-kn commented on test/core/propose_metablock.js
> +});
The value for the following should be asserted?

```
proposals[openKernelHeight][_proposal] = proposals[openKernelHeight][SENTINEL_PROPOSALS];
        proposals[openKernelHeight][SENTINEL_PROPOSALS] = _proposal;
```

2019-11-18 14:55 UTC, deepesh-kn commented on contracts/core/Core.sol
> +            "Validator must not have a non-zero begin height"
```suggestion
            "Validator must not have a non-zero begin height."
```

2019-11-18 14:55 UTC, deepesh-kn commented on contracts/core/Core.sol
> +            "Proposal set has already been initialised at this height."
```suggestion
            "Proposal set has already been initialized at this height."
```

2019-11-26 09:34 UTC, pgev commented on test/core/join.js
> +        'The core must be running..',
Fixed.

2019-11-26 09:49 UTC, pgev commented on test/core/join_during_creation.js
> +      assertConfigInCreation(config.mockCore);
It's not strictly needed (it's just an assertion). Here, it asserts that after one validator has joined the state of core has not been changed. If that's confusing, we could move it as assumably there is other test testing this scenario in depth.

2019-11-26 09:52 UTC, pgev commented on test/core/join_during_creation.js
> +});
Can you please elaborate more what do you mean?

2019-11-26 09:54 UTC, pgev commented on contracts/core/Core.sol
> +            "Validator must not have a non-zero begin height"
Fixed.

2019-11-26 09:54 UTC, pgev commented on contracts/core/Core.sol
> +            "Proposal set has already been initialised at this height."
Ok.

2019-11-26 13:16 UTC, pgev commented on test/core/join.js
> +
Your guess is correct. Not all conditions can appear. I've converted the following two ones into assert:
  * Begin height cannot be less than kernel height.
  * Validator must not have a non-zero begin height

I've added test case for the last point.

2019-11-26 13:27 UTC, pgev commented on test/core/join_during_creation.js
> +
The 2. and 3. can not be reached. They are currently `assert` instead of `require`.

Can you elaborate more on 1. point. What do you mean?

2019-11-26 14:15 UTC, pgev commented on test/core/open_metablock.js
> +    });
- Quorum is asserted.
- Asserted that proposal set has been initialized.

2019-11-26 14:44 UTC, deepesh-kn commented on test/core/join_during_creation.js
> +
I was referring to https://github.com/mosaicdao/mosaic-1/blob/599ad1736188b1025a6a3211a64f3abe8e5071cd/contracts/core/Core.sol#L935

But I can see that this is called from `openMetablock`  and `joinDuringCreation` 
So this condition should not occur.
Do we need `newProposalSet`? 

But I will not block this PR for this, as this PR is for unit test, we can discuss this offline.

2019-11-27 10:42 UTC, pgev commented on test/core/join_during_creation.js
> +
This function is internal and it should be `assert` instead of `require`. I've updated it.

2019-11-27 13:26 UTC, deepesh-kn approved these changes

2019-11-27 13:29 UTC, merged