Refactors Consensus::enterCommittee
OpenST/compute pull request #161
Opened 2020-01-08 09:36 UTC by pgev

fixes #147

2020-01-09 06:42 UTC, abhayks1 commented
@pgev Is it available for review?
Travis tests are red 🔴

2020-01-09 10:12 UTC, pgev commented
@abhayks1 I've rebased and fixed failing tests. It's again ready for review.

2020-01-10 08:12 UTC, abhayks1 requested changes
Nice work 👍 
Please see inline comments.

2020-01-10 08:12 UTC, abhayks1 commented on contracts/core/Core.sol
> +    function isValidator(address _account, uint256 _metablockHeight)
A lot of code between `isActiveValidator` and `isValidator` is common. We can refactor the common code to a private method with parameters `account, metablockHeight`. isActiveValidator can pass` openKernelHeight` as metablockHeight

What do you think?

2020-01-10 08:12 UTC, abhayks1 commented on contracts/core/Core.sol
> +     */
We should add documentation for function arguments and and return values as per dev guidelines. 
Similar comment for isActiveValidator method.

2020-01-10 08:12 UTC, abhayks1 commented on contracts/consensus/Consensus.sol
>          address _validator,
I feel `_validator` argument should come before `_validatorMetachainId`, _`validatorMetablockHeight`.
A validator is entering into committee. `_validatorMetachainId` and `_validatorMetablockHeight` seems like they are the properties of a validator. The `_validator` argument significance is strong enough to be prefixed before `_validatorMetachainId` and `_validatorMetablockHeight`
@pgev @deepesh-kn what do you think? It's an interface change.

2020-01-10 08:12 UTC, abhayks1 commented on contracts/consensus/Consensus.sol
> +        if (validatorMetablock.roundBlockNumber >= formationHeight) {
I think the logic of evaluating `checkValidatorForHeight` can be refactored to private/internal method 🤔.
enterCommittee method has grown significantly.

2020-02-11 12:58 UTC, pgev commented
Closing the PR for now. Will add into #147 as a note for later reference if needed.

2020-02-11 12:58 UTC, closed without merging