Implementation of GenesisUtmost contract
OpenST/compute pull request #217
Opened 2020-01-23 10:33 UTC by abhayks1

- Implementation of GenesisUtmost contract.

- It has `TOTAL_SUPPLY` as constant value.

Fixes #173

2020-01-23 12:56 UTC, deepesh-kn requested changes
This will not be a constant in the contract but a variable.

`uint256 public genesisTotalSupply;`

The value will be set in the genesis block, depending upon the deposit amount of validators.

2020-01-24 06:56 UTC, abhayks1 commented
It's available for review.

2020-01-24 07:01 UTC, jayeshbairagi approved these changes
Looks good to me

2020-01-24 07:06 UTC, deepesh-kn approved these changes

2020-01-24 07:54 UTC, merged