Changed the function type of commitMetablock of Consensus contract from public to external
OpenST/compute pull request #281
Opened 2020-02-17 10:34 UTC by bruce9steve

- Changed the function type of commitMetablock in Consensus contract from "public" to "external".

2020-02-17 12:01 UTC, 0xsarvesh requested changes
Thanks 👍  
Some feedback.

2020-02-17 12:01 UTC, 0xsarvesh commented on contracts/consensus/Consensus.sol
> +        bytes32 metablockHash = goToCommittedRound(_metachainId);
This is call twice in below functions : 
1. assertCommit
2. commitStateRoot

2020-02-17 12:01 UTC, 0xsarvesh commented on contracts/consensus/Consensus.sol
> +        CoreI core = assignments[_metachainId];
Core address is read three times. Is it possible to optimise this?

2020-02-17 12:01 UTC, sarvesh-ost commented on contracts/consensus/Consensus.sol
> +    function commitStateRoot(
It's more readable if event is emitted by external function instead of private.

2020-02-17 12:01 UTC, sarvesh-ost commented on contracts/consensus/Consensus.sol
> +    function commitStateRoot(
Naming can be improved.

2020-02-18 09:44 UTC, bruce9steve commented
As discussed with @deepesh-kn I am moving this ticket to parking lot.

2020-03-15 19:27 UTC, benjaminbollen commented
Thanks, but I will close this.

2020-03-15 19:27 UTC, closed without merging