Committe contract unit test cases
OpenST/compute pull request #32
Opened 2019-11-21 11:59 UTC by gulshanvasnani

PR contains changes to add negative unit test cases for committee status.

2019-11-26 09:04 UTC, pgev requested changes
Thanks for changes.

Negative tests asserting correct states of functions became complicated with the current approach.
I would propose to introduce a MockCommittee contract that inherits from the actual one and adds a new function `setCommitteeState`. This will update the `committeeState` variable of the contract and tests would become much simpler and straightforward.

2019-11-26 09:04 UTC, pgev commented on test/committee/utils.js
> +  for (let i = 0; i < committeeSize + 2; i += 1) {
What is "+2" here for?

2019-11-26 09:04 UTC, pgev commented on test/committee/utils.js
> +      distance: this.distanceToProposal(
What is `this` in this case?

2019-11-26 09:04 UTC, pgev commented on test/committee/utils.js
> +function getMemberDistance(accountProvider, dislocation, proposal, committeeSize, compareFn) {
Proposal:
  * getMemberDistance -> getCommitteeMembers
  * compareFn -> sortPredicate

2019-11-26 09:04 UTC, pgev commented on test/committee/utils.js
> +function compare(a, b) {
Proposal:
  * compareMemberDistance(firstMember, secondMember)

2019-11-26 09:04 UTC, pgev commented on test/committee/activate_committee.js
> +    it('should fail if committee is in open phase status', async () => {
As it has been decided to assert the condition in all other states, we are missing "CommitteeStatus::Closed" state here.

2019-11-26 09:04 UTC, pgev commented on test/committee/challenge_committee.js
> +    it('should fail if committee is in open phase state ', async () => {
As it has been decided to assert the condition in all other states, we are missing `CommitteeStatus::Closed` and `CommitteeStatus::Invalid` states here.

2019-11-26 09:04 UTC, pgev commented on test/committee/close_commit_phase.js
> +    it('should fail if committee is in open phase status', async () => {
As it has been decided to assert the condition in all other states, we are missing `CommitteeStatus::Closed` state here.

2019-11-26 09:04 UTC, pgev commented on test/committee/cooldown_committee.js
> +    it('should fail if committee is in cooldown state', async () => {
As it has been decided to assert the condition in all other states, we are missing `CommitteeStatus::Closed` state here.

2019-11-28 07:00 UTC, gulshanvasnani commented on test/committee/cooldown_committee.js
> +    it('should fail if committee is in cooldown state', async () => {
Done

2019-11-28 07:00 UTC, gulshanvasnani commented on test/committee/close_commit_phase.js
> +    it('should fail if committee is in open phase status', async () => {
Done

2019-11-28 07:00 UTC, gulshanvasnani commented on test/committee/challenge_committee.js
> +    it('should fail if committee is in open phase state ', async () => {
Done

2019-11-28 07:04 UTC, gulshanvasnani commented on test/committee/utils.js
> +  for (let i = 0; i < committeeSize + 2; i += 1) {
It is used for *challengeCommittee* transaction.
The code is already there. I moved it to Utils
https://github.com/mosaicdao/mosaic-1/blob/develop/test/committee/challenge_committee.js#L54

2019-11-28 07:16 UTC, gulshanvasnani commented on test/committee/activate_committee.js
> +    it('should fail if committee is in open phase status', async () => {
Done

2019-11-28 07:16 UTC, gulshanvasnani commented on test/committee/utils.js
> +function compare(a, b) {
Done

2019-11-28 07:16 UTC, gulshanvasnani commented on test/committee/utils.js
> +function getMemberDistance(accountProvider, dislocation, proposal, committeeSize, compareFn) {
Done

2019-11-28 08:08 UTC, gulshanvasnani commented on test/committee/utils.js
> +      distance: this.distanceToProposal(
*this* is not needed. So removed it.

2019-12-04 07:35 UTC, gulshanvasnani commented
As the implementation can change, so negative unit test cases not required now.

2019-12-04 07:35 UTC, closed without merging