Metachain id creation
OpenST/compute pull request #90
Opened 2019-12-04 13:19 UTC by gulshanvasnani

PR contains below changes :
- [x] Creation of metachain id.
- [ ] Update usage of chainid to metachain id.

2019-12-05 10:52 UTC, benjaminbollen commented on contracts/consensus/Consensus.sol
> +contract Consensus is MasterCopyNonUpgradable, CoreStatusEnum, ConsensusI, MosaicVersion {
move this second

2019-12-05 10:53 UTC, benjaminbollen commented on contracts/consensus/Consensus.sol
> +        "Metachain(address anchor)"
"MetachainId(address anchor)"

2019-12-06 09:18 UTC, benjaminbollen commented on contracts/consensus/Consensus.sol
>  // NOTE: consider either storing a linked list; or getting rid of it
you can remove this note pls; now the mapping for `anchors` is more sensible and we'll keep it as this

2019-12-06 09:27 UTC, benjaminbollen submitted a review, later dismissed
LGTM!

2019-12-09 07:56 UTC, jayeshbairagi requested changes
Minor typos

2019-12-09 07:56 UTC, jayeshbairagi commented on contracts/consensus/Consensus.sol
> +     * @param _anchor Anchor address of the new meta-chain.
Typo `meta-chain` should be `metachain`

2019-12-09 07:56 UTC, jayeshbairagi commented on contracts/consensus/Consensus.sol
> +     * @param _metachainId metachain id.
Typo `metachain` should be `Metachain`

2019-12-09 07:56 UTC, jayeshbairagi commented on contracts/consensus/Consensus.sol
>              "There is no core for the specified chain id."
Typo `chain` should be `metachain`

2019-12-09 09:28 UTC, jayeshbairagi submitted a review, later dismissed
LGTM

2019-12-09 09:31 UTC, deepesh-kn requested changes
One change: 
Chain id is still used in `test/core/utils.js` file.

Otherwise looks good. 👍

2019-12-09 09:31 UTC, deepesh-kn commented on test/core/open_metablock.js
> +      metachainId: web3.utils.keccak256('metachainid'),
We can get a random hash from utils.

2019-12-09 11:43 UTC, jayeshbairagi approved these changes

2019-12-09 11:44 UTC, deepesh-kn approved these changes

2019-12-09 11:53 UTC, jayeshbairagi commented
Tests are failing right now on Travis due to issue related to Ganache. The issue has been created here: https://github.com/mosaicdao/mosaic-1/issues/102.
All the tests are passing locally.

2019-12-09 11:54 UTC, merged